[package]
name = "elon-doge-bot"
version = "0.1.0"
authors = ["David Walsh <5778036+rhinodavid@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
